-- MySQL Script generated by MySQL Workbench
-- 06/28/17 22:03:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Interface
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Interface` ;

-- -----------------------------------------------------
-- Schema Interface
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Interface` DEFAULT CHARACTER SET utf8 ;
USE `Interface` ;

-- -----------------------------------------------------
-- Table `Interface`.`squares`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Interface`.`squares` ;

CREATE TABLE IF NOT EXISTS `Interface`.`squares` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `position` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `position_UNIQUE` (`position` ASC),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
